---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: metallb
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable
        namespace: gitops-system
      interval: 1m
spec:
  releaseName: metallb
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.12.0
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.3
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.3
    prometheus:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 192.168.1.150-192.168.1.155
