---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 0.40.0
      sourceRef:
        kind: HelmRepository
        name: grafana-loki-charts
        namespace: gitops-system
      interval: 1m
  # Depends on having prometheus-operator due to service monitor resources.
  dependsOn:
    - prometheus-operator
  values:
    loki:
      enabled: true
      serviceMonitor:
        enabled: true
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
