---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 2.11.1
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured
        namespace: gitops-system
      interval: 1m
spec:
  releaseName: kured
  helmVersion: v3
  chart:
    repository: https://weaveworks.github.io/kured
    name: kured
    version: 2.1.1
  values:
    image:
      repository: raspbernetes/kured
      tag: 1.4.5
