---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 2.2.1
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: gitops-system
      interval: 5m
  values:
    image:
      repository: raspbernetes/kured
      tag: 1.4.5
