---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: 2.11.1
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable
        namespace: gitops-system
      interval: 1m
  values:
    rbac:
      pspEnabled: true
    image:
      repository: gcr.io/google_containers/metrics-server-arm64
      tag: v0.3.6
    args:
      - --kubelet-insecure-tls=true
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
