---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: flagger
  helmVersion: v3
  chart:
    repository: https://flagger.app
    name: flagger
    version: 1.0.1
  values:
    image:
      repository: raspbernetes/flagger
      tag: 1.0.1
    rbac:
      pspEnabled: true
    crd:
      create: true
    meshProvider: nginx
    metricsServer: http://z-prometheus.observability:9090
