---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux
spec:
  interval: 5m
  chart:
    spec:
      chart: flagger
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: flagger-charts
        namespace: gitops-system
      interval: 1m
  values:
    image:
      repository: raspbernetes/flagger
      tag: v1.0.1
    rbac:
      pspEnabled: true
    crd:
      create: false
    meshProvider: nginx
    metricsServer: http://z-prometheus.observability.svc.cluster.local:9090
