---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: 1.10.3
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: gitops-system
      interval: 1m
  values:
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: 'letsencrypt-prod'
        nginx.ingress.kubernetes.io/auth-url: 'https://raspbernetes.com/oauth2/auth'
        nginx.ingress.kubernetes.io/auth-signin: 'https://raspbernetes.com/oauth2/start?rd=$escaped_request_uri'
      hosts:
        - sealed-secrets.raspbernetes.com
      path: /v1/cert.pem
      tls:
        - secretName: sealed-secrets.raspbernetes.com-tls
          hosts:
            - sealed-secrets.raspbernetes.com
