---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: gitops-system
      interval: 5m
  # Depends on prometheus-operator due to service monitor resources.
  # Temporarily disabled prometheus-operator due to namespace scope issue: https://github.com/fluxcd/helm-controller/issues/70
  # dependsOn:
  #   - prometheus-operator
  values:
    image:
      registry: docker.io
      repository: raspbernetes/external-dns
      tag: v0.7.3
      pullPolicy: IfNotPresent
    provider: cloudflare
    policy: upsert-only
    registry: 'txt'
    replicas: 1
    logLevel: debug
    rbac:
      create: true
      pspEnabled: true
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
        namespace: observability
    crd:
      create: true
    sources:
      - service
      - ingress
      - istio-gateway
      - istio-virtualservice
    domainFilters:
      - raspbernetes.com
    cloudflare:
      secretName: 'cloudflare-external-dns'
      email: 'michaelfornaro@gmail.com'
      proxied: true
