---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: speedtest-prometheus
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: speedtest-prometheus
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: billimek-charts
        namespace: gitops-system
      interval: 1m
  values:
    serviceMonitor:
      enabled: true
