---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: observability
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: prometheus-operator
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 9.3.1
  values:
    fullnameOverride: 'z'
    prometheusOperator:
      enabled: true
      manageCrds: true
      createCustomResource: true
      image:
        repository: quay.io/coreos/prometheus-operator
        tag: v0.40.0
        pullPolicy: Always
      tlsProxy:
        image:
          repository: raspbernetes/ghostunnel
          tag: v1.5.2
      admissionWebhooks:
        patch:
          image:
            repository: jettech/kube-webhook-certgen
            tag: v1.2.0
      configmapReloadImage:
        repository: jimmidyson/configmap-reload
        tag: v0.3.0
      prometheusConfigReloaderImage:
        repository: quay.io/coreos/prometheus-config-reloader
        tag: v0.40.0
    alertmanager:
      enabled: true
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: 'letsencrypt-prod'
          nginx.ingress.kubernetes.io/auth-url: 'https://raspbernetes.com/oauth2/auth'
          nginx.ingress.kubernetes.io/auth-signin: 'https://raspbernetes.com/oauth2/start?rd=$escaped_request_uri'
        hosts:
          - alert-manager.raspbernetes.com
        path: /
        tls:
          - secretName: alert-manager.raspbernetes.com-tls
            hosts:
              - alert-manager.raspbernetes.com
    grafana:
      enabled: true
      image:
        repository: grafana/grafana
        tag: 7.1.3
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: 'letsencrypt-prod'
          nginx.ingress.kubernetes.io/auth-url: 'https://raspbernetes.com/oauth2/auth'
          nginx.ingress.kubernetes.io/auth-signin: 'https://raspbernetes.com/oauth2/start?rd=$escaped_request_uri'
        hosts:
          - grafana.raspbernetes.com
        path: /
        tls:
          - secretName: grafana.raspbernetes.com-tls
            hosts:
              - grafana.raspbernetes.com
      sidecar:
        image:
          repository: raspbernetes/k8s-sidecar
          tag: 0.1.144
        imagePullPolicy: Always
      plugins:
        - natel-discrete-panel
        - pr0ps-trackmap-panel
        - grafana-piechart-panel
        - vonage-status-panel
        - grafana-worldmap-panel
        - btplc-status-dot-panel
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          istio-mesh-dashboard:
            url: https://grafana.com/api/dashboards/7639/revisions/22/download
            datasource: Prometheus
          istio-service-dashboard:
            url: https://grafana.com/api/dashboards/7636/revisions/22/download
            datasource: Prometheus
          istio-workload-dashboard:
            url: https://grafana.com/api/dashboards/7630/revisions/22/download
            datasource: Prometheus
          istio-performence-dashboard:
            url: https://grafana.com/api/dashboards/11829/revisions/22/download
            datasource: Prometheus
          istio-control-plane-dashboard:
            url: https://grafana.com/api/dashboards/7645/revisions/22/download
            datasource: Prometheus
          nginx-dashboard:
            url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
            datasource: Prometheus
          velero:
            url: https://grafana.com/api/dashboards/11055/revisions/2/download
            datasource: Prometheus
          flux:
            url: https://grafana.com/api/dashboards/10475/revisions/1/download
            datasource: Prometheus
          fluxv2:
            url: https://raw.githubusercontent.com/fluxcd/toolkit/master/manifests/monitoring/grafana/dashboards/control-plane.json
            datasource: Prometheus
          openebs-01:
            url: https://grafana.com/api/dashboards/12171/revisions/1/download
            datasource: Prometheus
          openebs-02:
            url: https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-pg-dashboard.json
            datasource: Prometheus
          speedtest:
            url: https://raw.githubusercontent.com/billimek/k8s-gitops/master/monitoring/prometheus-operator/grafana-dashboards/internet_speed.json
            datasource: Prometheus
      additionalDataSources:
        - name: loki
          type: loki
          access: proxy
          url: http://loki.logging.svc.cluster.local:3100
      downloadDashboardsImage:
        repository: curlimages/curl
        tag: 7.70.0
      admin:
        existingSecret: 'grafana-admin-creds'
        userKey: admin-user
        passwordKey: admin-password
      extraSecretMounts:
        - name: auth-generic-oauth-secret-mount
          secretName: auth-generic-oauth-secret
          defaultMode: 0440
          mountPath: /etc/secrets/auth_generic_oauth
          readOnly: true
      ## grafana Authentication can be enabled with the following values on grafana.ini
      # The full public facing url you use in browser, used for redirects and emails
      # https://grafana.com/docs/grafana/latest/auth/github/#enable-github-in-grafana
      # Note: auth.github.enabled=false until chart supports existingSecret functionality.
      # https://github.com/helm/charts/issues/22473
      grafana.ini:
        auth.github:
          enabled: true
          allow_sign_up: true
          scopes: user:email,read:org
          auth_url: https://github.com/login/oauth/authorize
          token_url: https://github.com/login/oauth/access_token
          api_url: https://api.github.com/user
          allowed_organizations: raspbernetes
          client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
          client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
        server:
          root_url: https://grafana.raspbernetes.com
    prometheus:
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: 'letsencrypt-prod'
          nginx.ingress.kubernetes.io/auth-url: 'https://raspbernetes.com/oauth2/auth'
          nginx.ingress.kubernetes.io/auth-signin: 'https://raspbernetes.com/oauth2/start?rd=$escaped_request_uri'
        hosts:
          - prometheus.raspbernetes.com
        path: /
        tls:
          - secretName: prometheus.raspbernetes.com-tls
            hosts:
              - prometheus.raspbernetes.com
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-cstor-sparse
              resources:
                requests:
                  storage: 10Gi
        ruleSelector: {}
        ruleNamespaceSelector: {}
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
    kube-state-metrics:
      image:
        repository: raspbernetes/kube-state-metrics
        tag: v1.9.5
