---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: dex
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: gitops-system
      interval: 1m
  # Depends on having the sealed secret dex-helm-values un-encrypted.
  # Temporarily disabled sealed-secrets due to namespace scope issue: https://github.com/fluxcd/helm-controller/issues/70
  # dependsOn:
  #   - sealed-secrets
  values:
    image: raspbernetes/dex
    imageTag: v2.24.0
    grpc: false
    ports:
      web:
        servicePort: 5556
    certs:
      image: gcr.io/google_containers/kubernetes-dashboard-init-arm
      web:
        create: false
      grpc:
        create: false
    telemetry: true
    config:
      issuer: https://dex.raspbernetes.com
      storage:
        type: kubernetes
        config:
          inCluster: true
      web:
        http: 0.0.0.0:5556
        # If enabled, be sure to configure tls settings above, or use a tool
        # such as let-encrypt to manage the certs.
        # Currently this chart does not support both http and https, and the port
        # is fixed to 5556
        #
        # https: 0.0.0.0:5556
        # tlsCert: /etc/dex/tls/tls.crt
        # tlsKey: /etc/dex/tls/tls.key
      frontend:
        theme: 'coreos'
        issuer: 'Example Co'
        issuerUrl: 'https://raspbernetes.com'
        logoUrl: https://example.com/images/logo-250x25.png
      expiry:
        signingKeys: '6h'
        idTokens: '24h'
      logger:
        level: debug
      oauth2:
        alwaysShowLoginScreen: false
        skipApprovalScreen: true
        responseTypes: ['code', 'token', 'id_token']
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: 'letsencrypt-prod'
        nginx.ingress.kubernetes.io/auth-url: 'https://raspbernetes.com/oauth2/auth'
        nginx.ingress.kubernetes.io/auth-signin: 'https://raspbernetes.com/oauth2/start?rd=$escaped_request_uri'
      hosts:
        - dex.raspbernetes.com
      path: /
      tls:
        - secretName: dex.raspbernetes.com-tls
          hosts:
            - dex.raspbernetes.com
  valuesFrom:
    - kind: Secret
      name: dex-helm-values
